services:
  app:
    build: .
    container_name: ista_aurora
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python main.py

  redis:
    image: redis:8.6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data

volumes:
  redis_data: